### ISSUE TITLE
Better error handling for the subscriber handler

### ISSUE THREAD

**Issue by asonnino** [MystenLabs/narwhal#120]
### Story
This task is part of the light client story https://github.com/MystenLabs/narwhal/issues/95

### Description
The subscriber handler deals with errors with a lot of ad-hoc prints and breaks.

**Comment by huitseeker** [comment]
@asonnino is this still useful?

**Comment by asonnino** [comment]
it is part of "better Sui-Narwhal" interface. I will be able to close all of these tickets once this PR completes:https://github.com/MystenLabs/sui/pull/3750#pullrequestreview-1061088897 Then I will know exactly what the interface should look like and I will be able to do a lot of cleanup

**Comment by akichidis** [comment]
Will close this as the code has now been refactored there.
