### ISSUE TITLE
Be able to deploy Narwhal in a "staging" environment

### ISSUE THREAD

**Issue by akichidis** [MystenLabs/narwhal#129]
### Description

Currently we do have a way to deploy Narwhal to Amazon and run a benchmark, which is definitely great and helpful. However, we are lacking the ability to have a constantly running network of Narwhal nodes in a way that "staging" (or development) environments do in a more traditional enterprise setup. Ideally, we would like to deploy in a (or a set of) AWS Amazon nodes a few Narwhal nodes in a primary-worker setup and let them run uninterrupted. Ideally we would like to have a nice CI/CD way to deploy after merging to a staging branch - or for simplicity we could just do it after the `main` branch. 

**Why is this important?**
* Currently we have no way to tell whether Narwhal is working correctly when left running for long periods (e.x weeks)
* Reveal issues/problems when up and running
* Have a deployment for developers to test the nodes in a real deployment (not just via our integration tests)

**Approach**
On its simplest form we would like to be able to trigger a (re)deployment after a CI/CD run on a `main` or `staging` branch. I am aware that things can get quite complex and certainly we are not looking for SRE level of work here, but something simple enough and robust that will allow us to deploy Narwhal in AWS Amazon. I would suggest looking into the following direction (some thoughts):

* Use [Terraform](https://www.terraform.io/) to ensure that whatever we build is reproducible and track changes. Highly recommended
* Build `Docker images` for our Narwhal node that will allow us to run either as primary or worker
* Integrate the image building process as part of our CI/CD to push images on `AWS ECR`
* Choose something like `ECS` to deploy the nodes. Alternatively, if we want to really abstract the deployment and node management process , we can use something like [AWS Fargate](https://aws.amazon.com/fargate/?nc2=h_ql_prod_ct_far)
* Start with a simple setup of `primary --> workers` node. We can expand to multiple primaries network as follow up
* Be able to see logs in `Cloudwatch` would be an extra bonus here

## Issue list:
- https://github.com/MystenLabs/narwhal/issues/211
- https://github.com/MystenLabs/narwhal/issues/212

**Comment by huitseeker** [comment]
Solved by continuous cluster deployments
