### ISSUE TITLE
Add some e2e tests

### ISSUE THREAD

**Issue by bmwill** [MystenLabs/narwhal#149]
Today we have a number of unit tests but I don't believe we have any end-to-end tests that are run with `cargo test` and it would be beneficial to have some sort of a smoke test other than needing to run the benchmarks.

**Comment by akichidis** [comment]
Totally agree on this @bmwill . We do actually have an engineering goal on our road map around it ([see. 1.3 End-to-end testing](https://www.notion.so/mystenlabs/Demo-Stage-1-Better-Engineering-planning-9a94e0afe86246aa839999a7c2405a4d#89a4f361d4674cec8347592c15c95782))  so we are definitely planning to work on this and dedicate the appropriate time to come up with something solid.

**Comment by huitseeker** [comment]
See also MystenLabs/sui#5194

**Comment by huitseeker** [comment]
We have e2e tests in the form of cluster tests (`.//test_utils/src/tests/cluster_tests.rs`and callers thereof) + long-running e2e tests (see ignored tests)
