### ISSUE TITLE
clarify calculation of BatchDigest

### ISSUE THREAD

**Issue by bmwill** [MystenLabs/narwhal#156]
Poking around the code it seems that BatchDigests are created via serializing a [`WorkerMessage::Batch`](https://github.com/MystenLabs/narwhal/blob/main/worker/src/batch_maker.rs#L121-L127) and then hashing it instead of what I would have expected which would be hashing the actual `Batch` type. Is there any context to why it's done the way it is today?

Also it seems non-ideal to craft the byte stream that is hashed by serializing via bincode vs some other canonical format. Is there something i'm missing on that front as well?

**Comment by huitseeker** [comment]
See also #188
