### ISSUE TITLE
Primary saturates the CPU under `>f` faults

### ISSUE THREAD

**Issue by asonnino** [MystenLabs/narwhal#159]
This issue is online to https://github.com/MystenLabs/sui/issues/1529. After some digging it seems that the Primary uses 100% of the CPU when it is running in an environment with more than 'f' faulty validators.

**Comment by huitseeker** [comment]
@bmwill We'll need to solve this as part of the Narwhal network spinup.

**Comment by huitseeker** [comment]
This should be significantly mitigated by #649.

**Comment by akichidis** [comment]
This is now quite old and maybe not relevant given the current status/issues we observe. Closing in favour of more recent efforts.
