### ISSUE TITLE
Securely cleanup the executor storage

### ISSUE THREAD

**Issue by asonnino** [MystenLabs/narwhal#191]
It is not clear how to security cleanup the executor storage. The following code does not work: https://github.com/MystenLabs/narwhal/blob/fecbfc9385e5599aed504d2b63de4b8763d4b6a2/executor/src/core.rs#L76-L85

The following problem may happen:

1. The subscriber adds a certificate C1 to its waiter until its payload X becomes available in the store
2. The corresponding payload downloaded
3. The executor core is about to execute the payload 
4. The subscriber adds a second certificate C2 to its waiter with the same payload X as certificate C1
5. C1 is executed and the store is purged right before the following future is polled: https://github.com/MystenLabs/narwhal/blob/fecbfc9385e5599aed504d2b63de4b8763d4b6a2/executor/src/subscriber.rs#L160-L170

As a result, C2 remains in the waiter forever. (Yes, this happened during a unit test)

**Comment by akichidis** [comment]
@asonnino is our assumption even in the case of `C1` that we'll _eventually_ receive the payload? I am sure there is some theory behind this, but how much would we break the protocol by putting a `timeout` when waiting for the payloads? Could this be a trigger to "reprocess" the message?

**Comment by asonnino** [comment]
No we can't have the timeout or we break safety or liveness. you break safety is you decide to ignore the timed out transactions and continue with the next ones, or you break liveness if you decide to shut down the node and panic

**Comment by asonnino** [comment]
I think the proper approach to this is a feedback communication between the core and the subscriber (but I haven't had time to properly thing about it)

**Comment by asonnino** [comment]
Also I think that other people using the codebase (somelier/celo?) will have the same issue

**Comment by huitseeker** [comment]
> Also I think that other people using the codebase (somelier/celo?) will have the same issue

I don't think so: we hash intents (including round #) in the digest definition for batches in our spec for them. As a consequence the mapping from headers to their payload should be injective.

Linked to #86 #156 #188
