### ISSUE TITLE
[remove_collections] introduce gRPC endpoint

### ISSUE THREAD

**Issue by akichidis** [MystenLabs/narwhal#194]
### Story

Parent story: https://github.com/MystenLabs/narwhal/issues/70

### Description

As part of this task a new gRPC endpoint should be introduced to `remove_collections`. The description of the endpoint can be found on the document here: https://www.notion.so/mystenlabs/Narwhal-Reference-Mempool-API-6e6268556f1249bc958d32f4bd1d5b77#889a21a374b74a9d8ee38fc40f7489b2

The endpoint should call the [block_remover](https://github.com/MystenLabs/narwhal/blob/fecbfc9385e5599aed504d2b63de4b8763d4b6a2/primary/src/block_remover.rs#L77) to achieve that.

**Comment by huitseeker** [comment]
closed in #224
