### ISSUE TITLE
Potential duplicate batch loading across components

### ISSUE THREAD

**Issue by akichidis** [MystenLabs/narwhal#209]
### Description

Currently in the codebase there are two different modules that allow us to synchronize (fetch) missing batches:
* [header_waiter](https://github.com/MystenLabs/narwhal/blob/bb701fcca37b2e404fc1a41e2bdc5192310d708a/primary/src/header_waiter.rs#L149)
* [block_synchronizer](https://github.com/MystenLabs/narwhal/blob/bb701fcca37b2e404fc1a41e2bdc5192310d708a/primary/src/block_synchronizer/mod.rs#L70)

both are triggered via different sources but it is possible to request batches for the same certificate(s) on the same time, leading to double processing. Ideally we would like only one of them to be responsible and avoid any such race conditions.

Although this is a potential problem, at the moment we have no data to say how frequently this will happen and how much of a problem this will be. Also, ideally we would like to transition using only one of them (the newly introduced `block_synchronizer`) so we can avoid having multiple places on our code which are responsible for the same behaviour.

**Comment by huitseeker** [comment]
see the related #163
