### ISSUE TITLE
[block_waiter] use block_synchronizer to synchronize missing blocks

### ISSUE THREAD

**Issue by akichidis** [MystenLabs/narwhal#223]
### Story

Parent story: https://github.com/MystenLabs/narwhal/issues/67

### Description

Extend the block synchronizer handler to call the `block_synchronizer` to fetch the missing payloads - if missing - and wire in to `block_waiter`.

Also, the `integration_tests` under the gRPC server should be modified to cover now the full successful scenario for retrieving missing collections.

**Comment by huitseeker** [comment]
Is this still relevant @akichidis ?

**Comment by akichidis** [comment]
That should be closed @huitseeker ...hmm weird, it seems that I moved it to "done" to the task board but didn't close the ticket. Doing this now.
