### ISSUE TITLE
[rounds]: introduce the rounds endpoint for the ProposerAPI

### ISSUE THREAD

**Issue by akichidis** [MystenLabs/narwhal#251]
### Epic

Parent epic: https://github.com/MystenLabs/narwhal/issues/44

### Description
We would like to introduce the `rounds` endpoint as part of the `ProposerAPI` . The output of the `rounds` endpoint reports the oldest and newest Narwhal rounds for which a collection from the input validator is present in the DAG. Since rounds are always increasing, oldest ≤ newest for all outputs of the rounds endpoint. More information can be found on the doc [here](https://www.notion.so/mystenlabs/Narwhal-Reference-Mempool-API-6e6268556f1249bc958d32f4bd1d5b77)

**Comment by huitseeker** [comment]
Fixed in #253
