### ISSUE TITLE
[bench] Flaky Bench

### ISSUE THREAD

**Issue by huitseeker** [MystenLabs/narwhal#252]
After #244 the bench seems to have suffered a large performance regression and is now flaky.
I have run it twice on a few commits to check:
https://github.com/MystenLabs/narwhal/commit/83e8bf2039ccea681c5abdb6f85d5e769b4c8e8d
https://github.com/MystenLabs/narwhal/commit/9126df4fcbd810d87bbc4ec85c694fe40df43951
https://github.com/MystenLabs/narwhal/commit/5cfb317c2a0dfe29190d1ba67281f8e99dc57799
https://github.com/MystenLabs/narwhal/commit/e680f285eab555edb6225fb31b63d3cb1b726dfe

Is it possible we're clobbering some interfaces?
For me, this is not reproducible locally.

**Comment by akichidis** [comment]
Same here, issue is not reproducible locally. More specifically this is what I get on my Apple Pro M1 , 10 Core, 16GB
```
-----------------------------------------
 SUMMARY:
-----------------------------------------
 + CONFIG:
 Faults: 0 node(s)
 Committee size: 4 node(s)
 Worker(s) per node: 1 worker(s)
 Collocate primary and workers: True
 Input rate: 50,000 tx/s
 Transaction size: 512 B
 Execution time: 15 s

 Header size: 1,000 B
 Max header delay: 200 ms
 GC depth: 50 round(s)
 Sync retry delay: 10,000 ms
 Sync retry nodes: 3 node(s)
 batch size: 500,000 B
 Max batch delay: 200 ms
 Max concurrent requests: 2 

 + RESULTS:
 Consensus TPS: 44,564 tx/s
 Consensus BPS: 22,816,661 B/s
 Consensus latency: 962 ms

 End-to-end TPS: 44,230 tx/s
 End-to-end BPS: 22,645,636 B/s
 End-to-end latency: 1,103 ms
```

**Comment by arun-koshy** [comment]
I could not see any additional added logging in #244

**Comment by huitseeker** [comment]
For historical purposes, here's the log of a primary before the change: https://gist.github.com/9f38c33e72e82acaf94e3505bd09e907
