### ISSUE TITLE
[header_waiter] potential bug when syncing batches from worker

### ISSUE THREAD

**Issue by akichidis** [MystenLabs/narwhal#286]
### Description
On the scenario where a primary node is processing a `header` whose payload (batches) hasn't been reached the authority, the `header_waiter` is being used to sync and fetch the missing payload. This is done by sending a `PrimaryWorkerMessage::Synchronize` to the worker node. By looking on the code here https://github.com/MystenLabs/narwhal/blob/f5dd2c29ffc131d3dbc5e9b2fca22464baae083a/primary/src/header_waiter.rs#L181

it seems that the address of the _peer worker node_ is resolved - not the "local" worker's address - and the synchronize request is sent to that worker. Giving an example, let's assume that we have two authorities, name them `A` and `B` each one having one primary and one worker node. And let's assume that authority A is processing a header that authority B has crafted and is now asking to sync the payload. It appears, that given the above code, the primary node of authority `A` **will ask directly** from the worker node of authority B to synchronize the batches. By looking on the corresponding worker code that is handling that request, it seems to me that this is not how such a request should be treated, but rather that request should be sent to the "local" worker node - meaning the worker node of authority A. Then the worker node of Authority A should contact the worker node of Authority B to fetch the missing payload.

So I would expect the code to be in this case the following (use the `&self.name` to fetch the local worker address instead of the header's author worker address):
```
.worker(&self.name, &worker_id)                                    
```

@asonnino @huitseeker could you please confirm the expected behaviour in the above scenario .

**Comment by akichidis** [comment]
> The original flow was the following:
> 
> * The primary detects it received a header containing an unknown payload. The primary knows when a payload is missing because its workers notify it of every new payload
> * The primary sends the sync request to its own worker
> * The worker checks if it didn't receive the payload in the meantime (this happens). If it didn't, it ensure it didn't already sent a sync request for this payload (this may happen as well). Finally, the worker sends a sync request to other workers.
> * Other workers will simply resend the missing batch using the normal batch-dissemination process.

Thanks so much for the reply @asonnino . Ok, given the above then `heder_waiter` should be changed to send the sync request to its own worker. I've also tested it locally and it seems that this functionality is now broken (missing payloads aren't synchronized via this mechanism). I'll open a PR for this.

**Comment by asonnino** [comment]
So I looked at the code and there was the bug you described right from the beginning (this is thus a bug that has 1+ years)

**Comment by Fomalhauthmj** [comment]
I found that in the facebookresearch's narwhal repo,this bug still exists.What can we do for future readers？

**Comment by asonnino** [comment]
> I found that in the facebookresearch's narwhal repo,this bug still exists.What can we do for future readers？

Sadly we don't have access to facebookresearch anymore but I can fixed it in this fork: https://github.com/asonnino/narwhal

**Comment by Fomalhauthmj** [comment]
In one word, this repo's narwhal system is continuously maintained.If you want to deep in the narwhal system, just follow this repo, right?

**Comment by asonnino** [comment]
Yes, MystenLabs maintains a production implementation of Narwhal (this repo). We also have a research prototype of Narwhal (https://github.com/asonnino/narwhal) that is less regularly maintained
