### ISSUE TITLE
[store] Feedback from use in fastnft 

### ISSUE THREAD

**Issue by gdanezis** [MystenLabs/narwhal#30]
We have now used the `DBKey` and `DBBatch` to implement persistence in fastnft. Some feedback:
* For a couple of operations we need atomic test-and-write, ie. to process orders we need to check lock values (none or the same) and then set them; for certificates we test objects / locks exist then do the write. The current abstractions do not provide a native (efficient) way of doing this, and therefore we need a mutex across this logic.
* Ser and Deser is really nice, and functional. BUT right now this is performed synchronously in the main thread that needs to have a mut lock on the database. The abstraction promotes doing ser / deser in the critical region (incidentally). It would probably be better to allow threads to have concurrent access to the DBMap, and internally protect operations using a mutex of RWlock.
* Its probably worth supporting a variant of typed `multi_get`, it is used often enough.

**Comment by huitseeker** [comment]
Closing in favor of https://github.com/MystenLabs/sui/issues/6018
