### ISSUE TITLE
[metrics] introduce telemetry metrics for primary & worker nodes

### ISSUE THREAD

**Issue by akichidis** [MystenLabs/narwhal#356]
### Description

Currently in Narwhal we do support logging but no telemetry metrics. In order to gain more insight on the nodes (primary & worker) operations, we would like to introduce telemetry metrics. We can use a similar approach that SUI took. Ultimately we would like to do the following:

1. define _which_ metrics would make sense to introduce (e.x number of batches created, latency, endpoints latencies etc)
2. introduce prometheus metrics
3. add an RPC server/gateway to collect the metrics and expose (to Grafana etc)

As reference adding the corresponding SUI [issue](https://github.com/MystenLabs/sui/issues/1455) and [PR](https://github.com/MystenLabs/sui/pull/1910)

**Comment by allan-bailey** [comment]
When you add metrics, please prefix them with something like narwhal_ or sui_ to enable easier discovery for humans.
Also, namespacing to prevent collisions with other metrics.
