### ISSUE TITLE
[metrics] introduce metrics to monitor buffers

### ISSUE THREAD

**Issue by akichidis** [MystenLabs/narwhal#423]
### Description

Following the work on [adding prometheus metrics](https://github.com/MystenLabs/narwhal/pull/393) we are looking to introduce a series of metrics to primarily monitor buffers (ex pending certificates to synchronise) across the code base (both primary & worker). As part of this PR we should introduce those metrics and expose via our standard prometheus mechanism. That will allow us to diagnose (or confirm) potential memory issues and gain more insight in general.

**Comment by huitseeker** [comment]
We would want to keep track of the memory footprint of:
- the consensus store in the Tusk & Bullshark deployments:
https://github.com/MystenLabs/narwhal/blob/e124cb99c1f2a2d4970cd2684d76db24e907e40f/consensus/src/bullshark.rs#L25
https://github.com/MystenLabs/narwhal/blob/7f0b458d9379710131ecb050746978d851f17c2c/consensus/src/tusk.rs#L90
(or whatever replaces them if they get replaced <LINK TO ISSUE HERE>)
- the DAG memory footprint in DAG (NW/external consensus) deployments:
https://github.com/MystenLabs/narwhal/blob/7f0b458d9379710131ecb050746978d851f17c2c/consensus/src/dag.rs#L43-L47

Only one of the above should be active in any deployment.

We should also keep track of:

- the synchronizer buffer in the primary cert synchronizer:
https://github.com/MystenLabs/narwhal/blob/7f0b458d9379710131ecb050746978d851f17c2c/primary/src/header_waiter.rs#L78
(see also [call points in the synchrnizer](https://github.com/MystenLabs/narwhal/blob/7f0b458d9379710131ecb050746978d851f17c2c/primary/src/synchronizer.rs#L123-L124))
- the worker batch cache:
https://github.com/MystenLabs/narwhal/blob/7f0b458d9379710131ecb050746978d851f17c2c/worker/src/processor.rs#L23

/cc @velvia

**Comment by akichidis** [comment]
> We would want to keep track of the memory footprint of:
> 
> * the consensus store in the Tusk & Bullshark deployments:
>   https://github.com/MystenLabs/narwhal/blob/e124cb99c1f2a2d4970cd2684d76db24e907e40f/consensus/src/bullshark.rs#L25
>   
>   https://github.com/MystenLabs/narwhal/blob/7f0b458d9379710131ecb050746978d851f17c2c/consensus/src/tusk.rs#L90
>   
>   (or whatever replaces them if they get replaced -LINK TO ISSUE HERE-)

regarding the `consensus store` this is backed by rocks DBMap, nothing kept in memory here, so this should be tracked by standard disk metrics (I believe we already have way to tell the available disk size).

**Comment by huitseeker** [comment]
> regarding the consensus store this is backed by rocks DBMap, nothing kept in memory here, so this should be tracked by standard disk metrics (I believe we already have way to tell the available disk size).

My mistake, I meant the neighboring `ConsensusState` : https://github.com/MystenLabs/narwhal/blob/e2191b35ef5d1542bcce9ae0340feb5957d2450b/consensus/src/consensus.rs#L21-L30
