### ISSUE TITLE
Fix the container image entry.sh script to send logs to stdout and stderr

### ISSUE THREAD

**Issue by allan-bailey** [MystenLabs/narwhal#455]
### Description

Currently the Narwhal image uses `entry.sh` to start a primary or worker instance, but redirects the logs
to files.  This makes it slightly more difficult to scrape those logs with Loki or other log scrapers.

We can instead just pull the logs from stdout/err from the containers and ship them to Loki.

### Steps to reproduce
None, just the entry.sh script redirecting to log files.

**Comment by akichidis** [comment]
+1 on the proposed approach. When introduced the `entry.sh` I considered writing the logs to files an easy way to go back an examine those - also simple for our customers (or whoever) intended to use. Now that we have loki it makes sense to ditch those files and just parse stdout/err. Let's make sure that [README](https://github.com/MystenLabs/narwhal/blob/6e86be42032de550764368c4a8a66e1472c68445/Docker/README.md?plain=1#L47) is updated and tell the user where they should expect to find the logs.
