### ISSUE TITLE
[safety] persist last_voted to avoid equivocation

### ISSUE THREAD

**Issue by huitseeker** [MystenLabs/narwhal#488]
### Description
We try to vote again on a header when processing its header / certificate:
https://github.com/MystenLabs/narwhal/blob/40f33bdc251b1e81b0194a559fa0a54ad1bc64dc/primary/src/core.rs#L265-L271
This can lead to a second vote by the same node in the case that the node has blown up its `last_voted` table :
https://github.com/MystenLabs/narwhal/blob/40f33bdc251b1e81b0194a559fa0a54ad1bc64dc/primary/src/core.rs#L77

This equivocation is unsafe. We should refactor the `last_voted` table so that:
- we only store the relevant information (last voted round per authority, rather than each)
- we vote in strictly increasing rounds per authority,
- we vote in a distance at most one from the latest voted round (can probably be made more strict @asonnino)

**Comment by akichidis** [comment]
Now this has been solved as part of https://github.com/MystenLabs/narwhal/pull/958
