### ISSUE TITLE
Check that all field scalars are valid.

### ISSUE THREAD

**Issue by punwai** [MystenLabs/narwhal#494]
In the #460 implementation, we do not check if the field scalars are valid. We need to mod r, by the size of the field on all the bytes to fix this.

**Comment by punwai** [comment]
```    // Some Seed
    let hk = Hkdf::<Sha3_256>::new(Some(&[1, 1]), &[
        255, 255, 255, 255, 255, 255, 255, 255,
        255, 1, 255, 1, 255, 3, 255, 255,
        255, 255, 255, 255, 4, 3, 255, 255,
        255, 11, 12, 53, 43, 43, 10, 11,
    ]);

    let mut okm = [0; 32];
    hk.expand(&[1], &mut okm)
        .map_err(|_| signature::Error::new())?;

    let big_okm = BigUint::from_bytes_be(okm.as_ref());
    let mod_num = BigUint::from_bytes_be(BLS12381_ORDER.as_ref());
    
    let okm = (big_okm % mod_num).to_bytes_be();

    let bls12381_secret_key =
        blst::min_sig::SecretKey::from_bytes(&bls_modulo).map_err(|_| signature::Error::new())?;
        
    Ok(())```

**Comment by punwai** [comment]
Also: Find the order for BLS12377.

**Comment by huitseeker** [comment]
The reduction modulo risks changing a scalar that is in non-canonical form into one that is canonical. As a consequence, this may make our system consider different two private keys that are actually the same, which can be dangerous.

The conservative approach, here is not scalar reduction, but to reject non-canonical (pre-reduced) scalars. I would support doing the check (for those libraries that do not already reject non-canonical scalars), but not the reduction.

/cc @kchalkias

**Comment by punwai** [comment]
This is just out of curiosity - please don't explain if busy - but why do we take any of such risks? We could have this modulo operation exclusive to the HKDF function, and simply reject in the from::bytes function.

**Comment by punwai** [comment]
The reason I'm pushing for this is because it is in the HKDF standard to mod the OKM

**Comment by punwai** [comment]
Closing this.
