### ISSUE TITLE
[proto] Batch exposed in `CollectionRetrievalResult`

### ISSUE THREAD

**Issue by huitseeker** [MystenLabs/narwhal#529]
Our `CollectionRetrievalResult` nests transactions in what appears to be a single batch. This batch is ephemeral and reflects collecting the transactions at the primary, rather than our actual notion of batch. We should either remove this wrapper, or name it in a disambiguated way.

https://github.com/MystenLabs/narwhal/blob/c312103d46189052f5f6a12ca32c233759d7ea21/types/proto/narwhal.proto#L59-L64

/cc @piersy

**Comment by akichidis** [comment]
@arun-koshy @huitseeker this is what I am proposing for the `GetCollections` endpoint. I also took into account the complexity that the current compiler is introducing on the clients when nesting `Result` is used and I believe we can probably make things a bit simpler by splitting into two parts:
1. the `collections` that have only the successfully retrieved collections
2. the `errors` field that contains the errors for the collections we didn't manage to retrieve

I've also removed entirely the concept of batches as for the 99% of the cases this won't be needed here. Even if we need that information (how transactions are grouped) this will be needed only for verification processes and we can always extend the `Collection` message with an extra field providing that info.

```
message GetCollectionsResponse {
    // List of successfully retrieved collections.
    repeated Collection collections = 1;
    
    // If failed to retrieve a collection then this will be added here
    repeated CollectionError errors = 2;
}

message Collection {
    // The collection's id
    CertificateDigest id = 1;

    // The transactions that are part of the collection
    repeated Transaction transactions = 2;
}

message Transaction {
    bytes transaction = 1;
}

message CollectionError {
    // The collection for which this error refers to
    CertificateDigest id = 1;

    enum CollectionErrorType {
        COLLECTION_NOT_FOUND = 0;
        COLLECTION_TIMEOUT = 1;
        COLLECTION_ERROR = 2;
    }
    CollectionErrorType type = 2;
}
```

**Comment by arun-koshy** [comment]
Everything looks good to me the only thing I am curious about is your switch to separate fields instead of a nested repeated `oneof`

> the complexity that the current compiler is introducing on the clients when nesting Result
Can you explain this further?

**Comment by akichidis** [comment]
> Everything looks good to me the only thing I am curious about is your switch to separate fields instead of a nested repeated `oneof`
> 
> > the complexity that the current compiler is introducing on the clients when nesting Result
> 
> Can you explain this further?

Sure, I should have explained that better. I am coming mostly from the client perspective. For instance to access a collection's transactions we need to do something like:
```
        match collection_result.retrieval_result.unwrap() {
            RetrievalResult::Batch(message) => {
                for t in message.transactions.unwrap().transaction {
                        // Do something with transaction
                        t.transaction
                }
            }
            RetrievalResult::Error(_) => {}
        }
```

the above is an example took from https://github.com/MystenLabs/narwhal/blob/1a672b3e10ddc465a9e06f3eacdac05db77afc2c/examples/src/demo_client.rs#L366

It seems to me that we need to do lots of nesting access and unwrapping (ex get the `retrieval_result` then unwrap, match etc) to get the transactions. That being said, is not the end of the world and thought that it might be quite convenient to have a simpler structure there. Also someone by just looking on the `errors` field can quickly figure out which failed. Again, not a big issue here.

**Comment by arun-koshy** [comment]
I don't mind changing it, but my argument to keep it would be because both fields in this case are mutually exclusive per `collection_id`. So it makes sense to use a `oneof` as only one can be set at a time. In terms of client access even if we remove the `oneof` and use two separate fields:
- Still need to check for both the success field and the error field
- The fields would require an unwrap because they would by default be optional in proto3

I also believe if we use a `oneof` the way the memory is allocated would be better because it only needs to allocate space for the largest of the specified fields as only one can be set at a time.

I updated [PR#536](https://github.com/MystenLabs/narwhal/pull/536) to reflect this, let me know what you think

**Comment by akichidis** [comment]
@arun-koshy thanks for the response. No problem from my side, I am not against the `oneof` but I thought it might be a bit simpler when accessing the collection it self, but I equally see the benefits you list so let's go  by keeping the `oneof` 👍
