### ISSUE TITLE
Comparison to facebook repository

### ISSUE THREAD

**Issue by vitruvvius** [MystenLabs/narwhal#554]
### Description
On GitHub there seems to be two implementations of Narwhal by the same two exact teams... what are the differences between the two (facebookresearch/narwhal & mystenlabs/narwhal)? if we were to deploy either one into production today for a simple distributed key value storage engine (write/read), which one would act as a better fit?

**Comment by huitseeker** [comment]
The `facebookresearch/narwhal` repository is a research prototype, and to the best of my knowledge, is no longer under active development.
By comparison, the present repository is actively developed, and aims to be more reliable from a production standpoint.
