### ISSUE TITLE
Cleanup Network

### ISSUE THREAD

**Issue by asonnino** [MystenLabs/narwhal#566]
### Description
Most of our networks (PrimaryToWorkerNetwork, PrimaryNetwork, WorkerNetwork) have a HashMap of address -> clients. When the committee changes and the network addresses change, the networks will simply expand this hash map but it is never cleaned up.

**Comment by huitseeker** [comment]
And we introduced a parallel `HashMap` of `BoundedExecutor`s in #559 indeed.
