### ISSUE TITLE
Prometheus metrics configuration should take a MultiAddr

### ISSUE THREAD

**Issue by huitseeker** [MystenLabs/narwhal#575]
The Prometheus metrics are exposed on an endpoint that, unlike the rest of the infrastructure, is not specified with a `Multiaddr` but with a `Socket`, parsed from an IPV4 in its default instance:
https://github.com/MystenLabs/narwhal/blob/28b2c89ded51f79386eed2e23c2a3325cfe3e8d6/config/src/lib.rs#L137-L150

It should be converted to use a `Multiaddr` like the rest of our config.

**Comment by akichidis** [comment]
FYI the conversation we had when introduced this https://github.com/MystenLabs/narwhal/pull/393#discussion_r910103634 .
