### ISSUE TITLE
Mop up KeyPair trait usage in restarter

### ISSUE THREAD

**Issue by asonnino** [MystenLabs/narwhal#579]
### Description

From @huitseeker 

Mop up the trait required to use `KeyPair`. We should be able to grab the most-constrained trait, i.e. KeyPair, and obtain the rest through projection, i.e. it's easier to do
```rust
foo<Keys: KeyPair>(
    ...
    Bar<Keys::PubKey>
    ...
)
```

rather than
```rust
foo<Keys: KeyPair<PubKey = PublicKey> + Signer<PublicKey::Sig> + Send + 'static, PublicKey: VerifyingKey> (
    ...
   Bar<PublicKey>
    ...
)
```

**Comment by huitseeker** [comment]
See https://github.com/MystenLabs/narwhal/pull/489#discussion_r928028508
