### ISSUE TITLE
[get_collections] introduce endpoint to retrieve the collections

### ISSUE THREAD

**Issue by akichidis** [MystenLabs/narwhal#67]
Epic: #44 

In order to allow our customers to integrate with Narwhal, one of the endpoints that we would like to introduce is the `get_collections`. As part of this story we are looking to expose an endpoint that will allow our clients to retrieve the transactions for a list of given headers / certificates. We'll call this a `collection`.

**Comment by huitseeker** [comment]
Closed in #140 and following PRs.
