### ISSUE TITLE
[read_causual] introduce endpoint to retrieve collection digests

### ISSUE THREAD

**Issue by akichidis** [MystenLabs/narwhal#69]
Epic: MystenLabs/narwhal#44 

In order to allow our customers to interface with our mempool we need to introduce a series of endpoints. One of those is the `read_causal` which will takes a collection digest and returns the collection digests encountered in a BFS of the graph, up to a commit boundary. On high level this endpoint will something like:
```
read_causal( collection_boundary: Digest ) -> Vec<Digest>
```

The behaviour of this endpoint on high level will work like this:
* Start by the last "checkpoint" that has been read previously read
* Start fetching collection digests by performing the BFS traversal (see MystenLabs/sui#5187 ) (probably up to a limit??)
* Return the results

**Comment by huitseeker** [comment]
Fixed in MystenLabs/narwhal#258
