### ISSUE TITLE
[get_collections] re-asses the storage model for worker batch store

### ISSUE THREAD

**Issue by akichidis** [MystenLabs/narwhal#72]
Story: #67 

Following the comments on the PR #66 , we should consider whether we should stick with the current storage model , meaning storing the `WorkerMessage::Batch(Batch)` serialised in database, or just store the `Batch` directly to allow us directly retrieve the required quantity.

Points that should be taken into account:
* potential performance penalties: it was deliberately chosen to store the serialised `WorkerMessage::Batch(Batch)` as is to avoid the serialisation cost

**Comment by huitseeker** [comment]
We have gone towards keeping the current storage model, but hashing with zero-copy deserialization:
https://github.com/MystenLabs/narwhal/pull/267
