### ISSUE TITLE
[tusk] allow Narwhal run without Tusk

### ISSUE THREAD

**Issue by akichidis** [MystenLabs/narwhal#74]
Currently on the repository Tusk is running by default without having the option to disable it. All the information is kept on its internal DAG. However, not all of our customers will want to run Narwhal with Tusk - in fact at the moment no-one will immediately want to. For that reason we should refactor the codebase to:
1. Give the ability to run a node with or without Tusk
2. When running without Tusk, the DAG should still be available to use in order for our customers to be able to perform `read_causal` requests #69 and `remove_collections` #70 . Those 2 issues are basically blocked until this work is finished first

On a high level we should aim to:
* allow the node to be run with a command line option to disable Tusk
* extract the common DAG parts of Tusk and create a component of "lightweight" Tusk to allow us form the DAG and advance rounds
* be able to boot the node with the above component

**Comment by huitseeker** [comment]
This is closed as of the demo stage: we run w/o Tusk
