### ISSUE TITLE
<title>

### ISSUE THREAD

**Issue by Elsant** [MystenLabs/narwhal#766]
### Description
When I try to run `cargo run --release --bin sui-node -- --config-path fullnode.yaml` as non root user ( as root also) I get an error
```
error: failed to get `config` as a dependency of package `sui-config v0.0.0 (/home/noder/sui/crates/sui-config)`

Caused by:
  failed to load source for dependency `config`

Caused by:
  Unable to update https://github.com/MystenLabs/narwhal?rev=fd070584b57304a8c7b94ee7af656a9375fc2095#fd070584

Caused by:
  object not found - no match for id (fd070584b57304a8c7b94ee7af656a9375fc2095); class=Odb (9); code=NotFound (-3)
```

### Steps to reproduce
Ubuntu 20
add non root user
```
adduser someuser
usermod -aG sudo someuser
```
Next steps from here
https://docs.sui.io/build/fullnode

**Comment by huitseeker** [comment]
Thanks @Elsant, this is probably an instance of https://github.com/MystenLabs/sui/issues/3980
Please retry, and reopen an issue on the sui repo if you still encounter this issue.
