### ISSUE TITLE
Committee channel being dropped and causing nodes to shutdown

### ISSUE THREAD

**Issue by arun-koshy** [MystenLabs/narwhal#805]
### Description
When trying to run the [demo](https://github.com/MystenLabs/narwhal/blob/main/examples/README.md) on main primaries consistently crash due to `thread 'tokio-runtime-worker' panicked at 'Committee channel dropped: RecvError(())'`

Seems to be an issue with `rx_reconfigure` being dropped.

```
result = self.rx_committee.changed() => {
      result.expect("Committee channel dropped");
      ...
  }
```

![Screen Shot 2022-08-16 at 3 32 18 PM](https://user-images.githubusercontent.com/97870774/185002944-81710de6-cdf6-47cc-9c02-90a300e3a9da.png)

### Steps to reproduce
1. `cd benchmark`
2. `fab demo`
3. Panicks can be seen in `narwhal/benchmark/logs/primary-*.log`

[primary-0.log](https://github.com/MystenLabs/narwhal/files/9355277/primary-0.log)

**Comment by huitseeker** [comment]
Interesting. Apparently https://github.com/MystenLabs/narwhal/pull/738 broke the local benches in CI, specifically parsing.
I can't reproduce the issue, though.

**Comment by arun-koshy** [comment]
Panics no longer reproducible via the client demo on main. @asonnino feel free to reopen if there were any changes you wanted to make with the `expects`.
