### ISSUE TITLE
[construct identifiers] form an identifier by using arbitrary data

### ISSUE THREAD

**Issue by akichidis** [MystenLabs/narwhal#94]
### Description

On various places in our codebase we have the need to construct request/look up keys that are based on some other arbitrary (but deterministically defined) data. One of the examples is on the `block_remover` component the `construct_request_key` method which forms a key based on provided block (certificate) ids. Those ids are used to form a unique request id which is further used on map look ups. This is now done in a bit naive way by just concatenating the id bytes, which is not ideal since:
* it leads to variable length keys 
* it can lead to quite big keys

As part of this task we want to define a way of creating more concise keys.

**Note:** Ideally we would like to implement a proper request/response pattern so we don't have to handle this logic on the core application level.

**Comment by akichidis** [comment]
FYI @huitseeker @bmwill @asonnino that's the ticket around finding a better solution for constructing an identifier (which we kind of do via the Hashing approach we followed on some of our PRs. Ideally though we want to implement the request/response pattern we talked today and is mentioned on the task here: https://github.com/MystenLabs/narwhal/issues/143

**Comment by bmwill** [comment]
Yeah I would hope that the networking layer/abstraction would be able to just handle this and be transparent to the actual application layer. We'll see how close we can get with the new networking library once I get to integrating it.
